config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :topics, only: [:index, :show]

  mount ActionCable.server => '/cable'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: ->(attrs) { attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html do
          redirect_to portfolios_path, notice: 'Portfolio was created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html do
          redirect_to portfolios_path, notice: 'Portfolio was updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def show; end

  def destroy
    @portfolio_item.destroy

    respond_to do |format|
      format.html do
        redirect_to portfolios_path, notice: 'Portfolio was deleted.'
      end
    end
  end

  private

  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :body,
      :main_image,
      :thumb_image,
      technologies_attributes: [:id, :name, :_destroy]
    )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.haml
= form_for(@portfolio_item) do |form|
  - if @portfolio_item.errors.any?
    - @portfolio_item.errors.full_messages.each do |error|
      = alert_generator error
  .row
    .col-md-6
      .form-group
        = form.label :title
        = form.text_field :title, class: "form-control"
      .form-group
        = form.label :subtitle
        = form.text_field :subtitle, class: "form-control"
      .form-group
        %label.btn.btn-primary
          Upload a main image file
          = form.file_field :main_image, style: 'display:none;'
      .form-group
        %label.btn.btn-primary
          Upload a thumb image file
          = form.file_field :thumb_image, style: 'display:none;'
    .col-md-6
      .form-group
        = form.label :body
        = form.text_area :body, class: "form-control", rows: 15
  .col-md-12      
    %h3 Technologies Used
    %div
      = form.fields_for :technologies do |technology_form|
        = render 'technology_fields', f: technology_form
      %div
        = link_to_add_association 'Add Technology', form, :technologies
    .form-group
      = form.submit "Save Portfolio Item", class: "btn btn-primary btn-block"

app/views/portfolios/_portfolio_item.html.haml
.col-md-4
  .card.mb-4.shadow-sm{"data-id": portfolio_item.id}
    = image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%'
    .card-body
      %p.card-text
        %span= link_to portfolio_item.title, portfolio_show_path(portfolio_item)
        = portfolio_item.subtitle

app/views/portfolios/_technology_fields.html.haml
.form-group.nested-fields
  = f.label :name
  = f.text_field :name, class: 'form-control'
  = link_to_remove_association 'Remove', f

app/views/portfolios/angular.html.haml
%h1 Angular Portfolio items

= link_to "New Item", new_portfolio_path if logged_in?(:site_admin)

- @angular_portfolio_items.each do |portfolio_item|
  %p= link_to portfolio_item.title, portfolio_show_path(portfolio_item)
  %p= portfolio_item.subtitle
  %p= portfolio_item.body
  = image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?
  = link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)
  = link_to "Delete", portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)

app/views/portfolios/edit.html.haml
.container.portfolio-container
  %h1 Edit this Portfolio Item
  = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/index.html.haml
.album.py-5.bg-light
  .container
    = source_helper "alert alert-warning"
    %div{class: "row #{"sortable" if logged_in?(:site_admin)}"}
      = render partial: 'portfolio_item', collection: @portfolio_items

app/views/portfolios/new.html.haml
.container.portfolio-container
  %h1 Create a new Portfolio Item
  = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/show.html.haml
.container.portfolio-container
  .row
    .col-md-7
      = image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' unless @portfolio_item.main_image.nil?
    .col-md-5
      %h1= @portfolio_item.title
      %hr
      %em= @portfolio_item.subtitle
      %p= @portfolio_item.body
      %h3 Technologies used
      - @portfolio_item.technologies.each do |t|
        %p= t.name
      - if logged_in?(:site_admin)
        %div
          = link_to 'Edit', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning'