config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :topics, only: [:index, :show]

  mount ActionCable.server => '/cable'
end

app/views/shared/_application_footer.html.haml
%footer.mastfoot.mt-auto
  .inner
    %p.app-footer= copyright_generator

app/views/shared/_application_nav.html.haml
%header.masthead.mb-auto
  .inner
    %h3.masthead-brand Florian Marchal
    %nav.nav.nav-masthead.app-nav
      = nav_helper 'nav-link', 'span'
      = login_helper 'nav-link'

app/views/shared/_blog_footer.html.haml
%footer.blog-footer
  %p= copyright_generator
  %p
    %a{href: "#"} Back to top 

app/views/shared/_blog_header.html.haml
%header.blog-header
  .container
    %h1.blog-title Pipala's Blog
    %span= link_to 'Write a new blog post', new_blog_path if logged_in?(:site_admin)
    %span= link_to 'Topics', topics_path
    

app/views/shared/_blog_nav.html.haml
.blog-masthead
  .container
    %nav.nav.d-flex
      = nav_helper 'p-3 nav-link', 'span'
      = login_helper 'p-3 nav-link'

app/views/shared/_blog_sidebar.html.haml
%aside.col-md-4.blog-sidebar
  .p-3.mb-3.bg-light.rounded
    %h4.font-italic About
    %p.mb-0
      I am a C# developer that is now specializing towards Rails development.
      %br
      %em #StriveForExcellence
  = source_helper("alert alert-info blog-sidebar-source")
  .p-3
    %h4 Topics
    - @site_bar_topics.each do |topic|
      %p= link_to topic.title, topic_path(topic)
  .p-3
    %h4.font-italic Elsewhere
    %ol.list-unstyled.social-links
      %li
        %a{href: "#"}= fa_icon "github"
      %li
        %a{href: "#"}= fa_icon "instagram"
      %li
        %a{href: "#"}= fa_icon "twitter"
      %li
        %a{href: "#"}= fa_icon "facebook"

app/views/shared/_nav.html.haml
%div{class: location }
  %div= link_to "Home", root_path
  %div= link_to "About", about_me_path 
  %div= link_to "Contact", contact_path
  %div= link_to "Blog", blogs_path
  %div= link_to "Portfolio", portfolios_path

app/views/shared/_portfolio_footer.html.haml
%footer.text-muted
  .container
    %p.float-right
      = link_to "View all Portfolio items", portfolios_path
      |
      %a{href: "#"} Back to top
    %p= copyright_generator

app/views/shared/_portfolio_header.html.haml
%section.jumbotron.text-center
  .container
    %h1.jumbotron-heading My Portfolio
    %p.lead.text-muted 
      You will find above the different accomplishments I have been able to do.
    %p
      = link_to "Find out more about me", about_me_path, class: "btn btn-primary my-2"
      = link_to "My Blog", blogs_path, class: "btn btn-secondary my-2"

app/views/shared/_portfolio_nav.html.haml
%header
  #navbarHeader.collapse.bg-dark
    .container
      .row
        .col-sm-8.col-md-7.py-4
          %h4.text-white About
          %p.text-muted 
            I am a C# developer that is now specializing towards Rails development.
            %br
            %em #StriveForExcellence
        .col-sm-4.offset-md-1.py-4
          %h4.text-white Explore
          %ul.list-unstyled
            = nav_helper 'text-white', 'li'
            %li= login_helper 'text-white'
  .navbar.navbar-dark.bg-dark.shadow-sm
    .container.d-flex.justify-content-between
      %a.navbar-brand.d-flex.align-items-center{href: "#"}
        %svg.mr-2{fill: "none", height: "20", stroke: "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", viewbox: "0 0 24 24", width: "20", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"}
          %circle{cx: "12", cy: "13", r: "4"}
        %strong Florian Marchal
      %button.navbar-toggler{"aria-controls" => "navbarHeader", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarHeader", "data-toggle" => "collapse", type: "button"}
        %span.navbar-toggler-icon
          